name: Analyze, Build and Deploy

"on":
  push:
    branches:
      - test

jobs:
  semantic-pull-request:
    name: "Semantic"
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    name: Build
    needs: [semantic-pull-request]
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3
      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.22.2
      - name: 📦 Install Dependencies
        run: |
          flutter pub get
      - name: 🛠️ Build the application
        run: flutter build web --dart-define=RECAPTCHA_V3_SITE_KEY=${{ secrets.RECAPTCHA_V3_SITE_KEY }} --wasm
      - name: ⬇️ Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build/web

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 📚 Checkout repo
        uses: actions/checkout@v3
      - name: ⬇️ Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build/web
      - name: 🎯 Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DANCE_CLUB_COMUNA_8 }}"
          channelId: test
          projectId: dance-club-comuna-8
